const products={
 noir:{name:"Noir Essence",price:2499,old:3299,notes:"Woody · Spicy · Bold",img:"images/noir.jpg",tag:"BEST SELLER",desc:"A bold and mysterious fragrance for those who lead, not follow. Rich woods, spices and amber create a signature that lingers."},
 blush:{name:"Blush Aura",price:2299,old:2999,notes:"Floral · Fruity · Fresh",img:"images/blush.jpg",tag:"NEW",desc:"A luminous floral-fruity fragrance with a soft, modern finish — fresh, expressive and easy to wear."},
 ocean:{name:"Ocean Drive",price:2199,old:2899,notes:"Citrus · Aquatic · Fresh",img:"images/ocean.jpg",tag:"POPULAR",desc:"Fresh citrus and aquatic notes made for bright days, clean shirts and an effortless presence."},
 amber:{name:"Amber Touch",price:2799,old:3699,notes:"Amber · Vanilla · Warm",img:"images/amber.jpg",tag:"LIMITED",desc:"Warm amber, creamy vanilla and a soft trail designed for evenings and unforgettable moments."}
};
function getCart(){return JSON.parse(localStorage.getItem("rozanaCart")||"[]")}
function saveCart(c){localStorage.setItem("rozanaCart",JSON.stringify(c));updateCount()}
function updateCount(){document.querySelectorAll("#cartCount").forEach(e=>e.textContent=getCart().reduce((n,x)=>n+x.qty,0))}
function addToCart(name,price,img,qty=1){const c=getCart();const x=c.find(i=>i.name===name);x?x.qty+=qty:c.push({name,price,img,qty});saveCart(c);toast(name+" added to your bag");}
function toast(t){const e=document.getElementById("toast");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function closeModal(id){document.getElementById(id)?.classList.remove("show")}
function openModal(id){document.getElementById(id)?.classList.add("show")}
function openSearch(){document.getElementById("searchModal")?.classList.add("show");setTimeout(()=>document.getElementById("searchInput")?.focus(),100)}
function closeSearch(){document.getElementById("searchModal")?.classList.remove("show")}
function initHome(){updateCount();const seen=sessionStorage.getItem("rozanaWelcome");if(!seen){setTimeout(()=>openModal("discountModal"),700);sessionStorage.setItem("rozanaWelcome","1")}
 const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>obs.observe(x));
 document.addEventListener("mousemove",e=>{document.documentElement.style.setProperty("--mx",e.clientX+"px");document.documentElement.style.setProperty("--my",e.clientY+"px")})
}
function loadProductPage(){updateCount();const key=new URLSearchParams(location.search).get("product")||"noir",p=products[key]||products.noir;document.title="ROZANA — "+p.name;document.getElementById("crumb").textContent=p.name;document.getElementById("tag").textContent=p.tag;document.getElementById("name").textContent=p.name;document.getElementById("notes").textContent=p.notes;document.getElementById("detailImg").src=p.img;document.getElementById("price").innerHTML=`₹${p.price.toLocaleString("en-IN")} <del>₹${p.old.toLocaleString("en-IN")}</del> <em>24% OFF</em>`;document.getElementById("description").textContent=p.desc;document.getElementById("detailNotes").textContent=p.notes+" · Long-lasting everyday signature.";window.currentProduct=p}
let currentQty=1;function changeQty(d){currentQty=Math.max(1,currentQty+d);document.getElementById("qty").textContent=currentQty}
function buyProduct(){const p=window.currentProduct;addToCart(p.name,p.price,p.img,currentQty)}
function renderCart(){updateCount();const c=getCart(),box=document.getElementById("cartItems");if(!c.length){box.innerHTML='<div class="form-card"><h2>Your bag is waiting.</h2><p>Explore the collection and add your first ROZANA fragrance.</p><a class="btn gold" href="index.html#shop">Shop fragrances →</a></div>';return}box.innerHTML=c.map((x,i)=>`<div class="cart-row"><img src="${x.img}"><div><h3>${x.name}</h3><p>₹${x.price.toLocaleString("en-IN")} · Qty ${x.qty}</p><button class="remove" onclick="removeItem(${i})">Remove</button></div><b>₹${(x.price*x.qty).toLocaleString("en-IN")}</b></div>`).join("");const sub=c.reduce((s,x)=>s+x.price*x.qty,0);const discount=localStorage.getItem("rozanaCoupon")==="1"?Math.min(1000,Math.round(sub*.2)):0;document.getElementById("subtotal").textContent="₹"+sub.toLocaleString("en-IN");document.getElementById("discount").textContent="-₹"+discount.toLocaleString("en-IN");document.getElementById("total").textContent="₹"+(sub-discount).toLocaleString("en-IN")}
function removeItem(i){const c=getCart();c.splice(i,1);saveCart(c);renderCart()}
function applyCoupon(){if(document.getElementById("coupon").value.trim().toUpperCase()==="ROZANA20"){localStorage.setItem("rozanaCoupon","1");toast("ROZANA20 applied · 20% off");renderCart()}else toast("Try coupon ROZANA20")}
function renderCheckout(){updateCount();const c=getCart();const box=document.getElementById("checkoutItems");const total=c.reduce((s,x)=>s+x.price*x.qty,0);if(box)box.innerHTML=c.map(x=>`<div><span>${x.name} × ${x.qty}</span><b>₹${(x.price*x.qty).toLocaleString("en-IN")}</b></div>`).join("")||"<p>Your bag is empty.</p>";if(document.getElementById("checkoutTotal"))document.getElementById("checkoutTotal").textContent="₹"+total.toLocaleString("en-IN")}
function placeOrder(e){e.preventDefault();const c=getCart();if(!c.length){alert("Your bag is empty.");return}const order={id:"RZ"+Date.now().toString().slice(-7),items:c,name:document.getElementById("fullName").value,phone:document.getElementById("phone").value,email:document.getElementById("email").value,address:document.getElementById("address").value,city:document.getElementById("city").value,pin:document.getElementById("pin").value,payment:document.querySelector('input[name="payment"]:checked').value,total:c.reduce((s,x)=>s+x.price*x.qty,0),created:new Date().toISOString()};localStorage.setItem("rozanaLastOrder",JSON.stringify(order));localStorage.removeItem("rozanaCart");localStorage.removeItem("rozanaCoupon");location.href="success.html"}
function renderSuccess(){updateCount();const o=JSON.parse(localStorage.getItem("rozanaLastOrder")||"null");if(!o){location.href="index.html";return}document.getElementById("orderNo").textContent="#"+o.id;document.getElementById("successDetails").innerHTML=`<div class="form-card"><p><b>Order total:</b> ₹${o.total.toLocaleString("en-IN")}</p><p><b>Payment:</b> ${o.payment}</p><p><b>Delivery:</b> ${o.address}, ${o.city} — ${o.pin}</p><p><b>Items:</b> ${o.items.map(x=>x.name+" × "+x.qty).join(", ")}</p></div>`}
function useExample(t){const x=document.getElementById("message");x.value=t;x.dispatchEvent(new Event("input"))}
function initCard(){updateCount();const ta=document.getElementById("message"),preview=document.getElementById("preview"),counter=document.getElementById("wordCounter");ta.addEventListener("input",()=>{let words=ta.value.trim()?ta.value.trim().split(/\s+/).length:0;if(words>200){ta.value=ta.value.trim().split(/\s+/).slice(0,200).join(" ");words=200}counter.textContent=words+" / 200 words";preview.textContent=ta.value||"Your message will appear here..."})}
function addCardToCart(){const msg=document.getElementById("message").value.trim();if(!msg){toast("Write your message first");return}const words=msg.split(/\s+/).filter(Boolean);if(words.length>200){toast("Please keep the note within 200 words");return}const c=getCart();c.push({name:"Personalised Handwritten Card",price:299,img:"images/rozana-reference.jpg",qty:1,message:msg});saveCart(c);toast("Personalised card added to your bag")}
document.addEventListener("DOMContentLoaded",()=>{updateCount();if(location.pathname.endsWith("index.html")||location.pathname==="/")initHome()})
